const participants = [
  {
    name: "Pawan Kolhe",
    college: "Amity University Mumbai",
    city: "Nagpur",
    github: "PawanKolhe",
    linkedin: "https://www.linkedin.com/in/kolhepawan/",
    website: "https://pawankolhe.com",
  },
  {
    name: "Saurabh Shukla",
    college: "Amity University Mumbai",
    city: "Navi Mumbai",
    github: "Fangston0",
    linkedin: "https://www.linkedin.com/in/saurabh-shukla-680425117/",
    website: "",
  },
  {
    name: "Ishaan Sunita Pandita",
    college: "Amity University Mumbai",
    city: "Navi Mumbai",
    github: "EmperorArthurIX",
    linkedin: "",
    website: "",
  },
  {
    name: "Phanindra Kavala",
    college: "Amity University Mumbai",
    city: "Rajahmundry",
    github: "phanindra7891",
    linkedin: "",
    website: "",
  },
  {
    name: "Neel Parihar",
    college: "Amity University Mumbai",
    city: "Mumbai",
    github: "NeelParihar",
    linkedin: "https://www.linkedin.com/in/neel-parihar/",
    website: "",
  },
  {
    name: "Punit Baviskar",
    college: "Amity University Mumbai",
    city: "Pune",
    github: "puneetb22",
    linkedin: "https://www.linkedin.com/in/puneetb22/",
    website: "https://punitbaviskar.netlify.app/",
  },
];
